---
title: Poppy Coffee Co.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    img-url: ''
    categories: Shows
    img-url: ''
    card-img: ''
    show-snip: ''
    book-url: ''
    from-price: ''
    gallery:
      img: ''
clubBenefits:
    - Benefit 1
    - Benefit 2
    - Benefit 3
    - Benefit 4
email:
description: <p>You can't move for coffee chains in town centres these days– after all that's where the crowds are.</p><p>If you're lucky you may find a dedicated artisan coffee shop tucked away somewhere. There you will find the perfect cup that makes you want to be late for work. The freshest of beans ground individually for your cup, not going stale in a hopper; sumptuous micro-foam on your latte or cappuccino, not weak froth. And the friendly welcome given to those in the know.</p>
baseurl: ''
url: http://theatreclub.superbreak.com
markdown: kramdown
